schoolsSystems/Models/DropMenu/CityDropMenu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace schoolsSystems.Models
{
    public class CityDropMenu
    {
        public int CityId { get; set; }
        public IEnumerable<City> cities { get; set; }
    }
}

schoolsSystems/Models/DropMenu/DropMenu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace schoolsSystems.Models.DropMenu
{
    public class DropMenu<T>
    {
        public int Id { get; set; }
        public IEnumerable<T> list { get; set; }
    }
}

schoolsSystems/Models/DropMenu/FormDropMenu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace schoolsSystems.Models.DropMenu
{
    public class FormDropMenu
    {
        public int FormId { get; set; }
        public IEnumerable<Form> forms { get; set; }
    }
}

schoolsSystems/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using schoolsSystems.Models;
using schoolsSystems.Models.DropMenu;

namespace schoolsSystems.Controllers
{
    public class FormController : Controller
    {
        EMEntities db;
        //
        // GET: /Form/
        public FormController(){
            db=new EMEntities();
        }
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult List(int schoolId)
        {
            List<Form> forms = db.Form.ToList();
            ViewBag.schoolId = schoolId;
            return PartialView(forms);
        }
        public PartialViewResult DropMenu(int formId)
        {
            return PartialView(new FormDropMenu { FormId= formId, forms = db.Form.ToList() });
        }
    }
}

schoolsSystems/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using schoolsSystems.Models;

namespace schoolsSystems.Controllers
{
    public class ListController : Controller
    {
        EMEntities db;
        public ListController()
        {
            db = new EMEntities();
        }
        //
        // GET: /List/

        public PartialViewResult Subject()
        {
            return PartialView();
        }

    }
}

schoolsSystems/Controllers/SchoolFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using schoolsSystems.Models;
using schoolsSystems.Models.DropMenu;

namespace schoolsSystems.Controllers
{
    public class SchoolFormController : Controller
    {
        EMEntities db;
        public SchoolFormController(){
            db=new EMEntities();
        }
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "admin")]
        public ActionResult Edit(SchoolForm schoolForm)
        {
            ViewBag.BodyTitle = "Добавить класс";
            if (ModelState.IsValid)
            {
                db.SchoolForm.Add(schoolForm);
                db.SaveChanges();
            }
            return RedirectToAction("Pupils","School",new {schoolId = schoolForm.SchoolId});
        }
        [Authorize(Roles = "admin")]
        public ActionResult Create(int SchoolId = 0, int SchoolFormId = 0)
        {
            School school = db.School.FirstOrDefault(s => s.Id == SchoolId);
            ViewData.Add("school", school);
            ViewBag.BodyTitle = "Добавить класс";
            SchoolForm sf = new SchoolForm();
            sf.SchoolId = SchoolId;
            return View("Edit", sf);
        }
        public PartialViewResult List(int SchoolId)
        {
            List<SchoolForm> forms = db.SchoolForm.Where(sc=>sc.SchoolId==SchoolId).ToList();
            return PartialView(forms);
        }
        public PartialViewResult DropMenu(int SchoolFormId,int SchoolId)
        {
            return PartialView(new DropMenu<SchoolForm> { Id = SchoolFormId, list = db.SchoolForm.Where(sf=>sf.SchoolId==SchoolId).ToList() });
        }
    }
}

schoolsSystems/Views/SchoolForm/DropMenu.cshtml
@model schoolsSystems.Models.DropMenu.DropMenu<schoolsSystems.Models.SchoolForm>
<div>
    @Html.DropDownList("SchoolFormId", new SelectList(Model.list,"Id","Name"), "Выберите класс", new { @id = "SchoolFormId" })
</div>

schoolsSystems/Views/SchoolForm/Edit.cshtml
@model schoolsSystems.Models.SchoolForm

@{
    ViewBag.Title = "Класс Школы";
    Layout = "~/Views/Shared/_SchoolLayout.cshtml";
}

<h2>Класс Школы</h2>
@using (Html.BeginForm("Edit", "SchoolForm", FormMethod.Post))
{

    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model=>model.SchoolId)

    <div>
        Класс @Html.Action("DropMenu", "Form", new { formId = Model.FormId })
    </div>
    <div>
        Буква @Html.Action("DropMenu", "FormLetter", new { formLetterId = Model.FormLetterId})
    </div>
    <p>
        <input type="submit" value="Сохранить" />
    </p>
}

schoolsSystems/Views/SchoolForm/List.cshtml
@model IEnumerable<schoolsSystems.Models.SchoolForm>

@foreach (var form in Model)
{
    <div>
        @Html.ActionLink(form.Name, "Index", "Pupil", new { SchoolId = form.SchoolId, SchoolFormId = form.Id }, null)
    </div>
}