schoolsSystems/Controllers/TimeTableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using schoolsSystems.Models;

namespace schoolsSystems.Controllers
{
    public class TimeTableController : Controller
    {
        EMEntities db;

        public TimeTableController()
        {
            db = new EMEntities();
        }
        //
        // GET: /TimeTable/

        public ActionResult Index(int schoolId=0,int schoolFormId=0)
        {
            School school = db.School.FirstOrDefault(s => s.Id == schoolId);
            ViewData.Add("school", school);
            List<TimeTable> timeTable = db.TimeTable.Where(tt => tt.SchoolId == schoolId && tt.SchoolFormId==schoolFormId).ToList();
            ViewBag.BodyTitle = "Расписание";
            ViewBag.schoolId = schoolId;
            ViewBag.schoolFormId = schoolFormId;
            return View(timeTable);
        }
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int schoolId=0,int schoolFormId=0,int dayOfWeek=0 )
        {
            School school = db.School.FirstOrDefault(s => s.Id == schoolId);
            ViewData.Add("school", school);
            IEnumerable<TimeTable> timeTable = db.TimeTable.Where(tt => tt.SchoolId == schoolId && tt.SchoolFormId == schoolFormId && tt.DayOfWeek == dayOfWeek);
            List<TimeTable> res = new List<TimeTable>();
            for (int i = 1; i < 10; i++)
            {
                TimeTable lesson = timeTable.FirstOrDefault(tt=>tt.LessonNumber==i);
                if(lesson==null)
                    res.Add(new TimeTable{SchoolId=schoolId,SchoolFormId=schoolFormId,DayOfWeek=dayOfWeek,LessonNumber=i});
                else
                    res.Add(lesson);
            }
            ViewBag.BodyTitle = "Редактирование расписание";
            ViewData.Add("subjects",db.Subject.ToList());
            return View(new DayOfTimeTable { SchoolId=schoolId,SchoolFormId=schoolFormId,listOfDay=res});
        }
        public ActionResult Save(DayOfTimeTable dayOfTimeTable)
        {
            List<TimeTable> onSave = dayOfTimeTable.listOfDay.Where(tt => tt.SubjectId != 0).ToList();
            foreach (var tt in onSave)
            {
                db.TimeTable.Add(tt);
            }
            db.SaveChanges();
            return RedirectToAction("Index", new { schoolId=dayOfTimeTable.SchoolId,schoolFormId=dayOfTimeTable.SchoolFormId});
        }

        public PartialViewResult ListOfDay(List<TimeTable> timeTable, int dayOfWeek)
        {
            return PartialView(timeTable.Where(tt=>tt.DayOfWeek==dayOfWeek).ToList());
        }
    }
}

schoolsSystems/Views/TimeTable/Edit.cshtml
@model schoolsSystems.Models.DayOfTimeTable

@{
    ViewBag.Title = "Редактирование";
    Layout = "~/Views/Shared/_SchoolLayout.cshtml";
}

<h2>Редактирование расписания</h2>
@using (Html.BeginForm("Save","TimeTable",FormMethod.Post))
{   
    @Html.HiddenFor(m=>m.SchoolId)
    @Html.HiddenFor(m=>m.SchoolFormId)
    <div>
        @Html.EditorFor(m=>m.listOfDay)
    </div>
    <input type="submit" name="Сохранить"/>
}

schoolsSystems/Views/TimeTable/Index.cshtml
@model IEnumerable<schoolsSystems.Models.TimeTable>
@{
    ViewBag.Title = "Расписание";
    Layout = "~/Views/Shared/_SchoolLayout.cshtml";
}
<div class="monday">
    Понедельник @Html.ActionLink("(редактировать)", "Edit", new { schoolId=ViewBag.schoolId,schoolFormId=ViewBag.schoolFormId,dayOfWeek=1})
    @Html.Action("ListOfDay", new {timeTable=@Model,dayOfWeek=1})
</div>
<div class="tuesday">
    Вторник @Html.ActionLink("(редактировать)", "Edit", new { schoolId = ViewBag.schoolId, schoolFormId = ViewBag.schoolFormId, dayOfWeek = 2 })
    @Html.Action("ListOfDay", new { timeTable = @Model, dayOfWeek = 2 })
</div>
<div class="wednesday">
    Среда @Html.ActionLink("(редактировать)", "Edit", new { schoolId = ViewBag.schoolId, schoolFormId = ViewBag.schoolFormId, dayOfWeek = 3 })
    @Html.Action("ListOfDay", new { timeTable = @Model, dayOfWeek = 3 })
</div>
<div class="thursday">
    Четверг @Html.ActionLink("(редактировать)", "Edit", new { schoolId = ViewBag.schoolId, schoolFormId = ViewBag.schoolFormId, dayOfWeek = 4 })
    @Html.Action("ListOfDay", new { timeTable = @Model, dayOfWeek = 4 })
</div>
<div class="friday">
    Пятница @Html.ActionLink("(редактировать)", "Edit", new { schoolId = ViewBag.schoolId, schoolFormId = ViewBag.schoolFormId, dayOfWeek = 5 })
    @Html.Action("ListOfDay", new { timeTable = @Model, dayOfWeek = 5 })
</div>
<div class="saturday">
    Суббота @Html.ActionLink("(редактировать)", "Edit", new { schoolId = ViewBag.schoolId, schoolFormId = ViewBag.schoolFormId, dayOfWeek = 6 })
    @Html.Action("ListOfDay", new { timeTable = @Model, dayOfWeek = 6 })
</div>

schoolsSystems/Views/TimeTable/ListOfDay.cshtml
@model IEnumerable<schoolsSystems.Models.TimeTable>
@for (int i = 1; i < 10; i++)
{
    schoolsSystems.Models.TimeTable lesson = Model.FirstOrDefault(tt => tt.LessonNumber == i);
    <div>@i @(lesson == null ? "-" : lesson.Subject.Name)</div>
}